### ISSUE TITLE
Request for Open Sourcing Qt Code of TMCL IDE for Customization and Learning Purposes

### ISSUE THREAD

**Issue by yasir-shahzad** [trinamic/TMCL-Script-Examples#2]
Could you please open-source the Qt code for TMCL IDE? This will aid us in learning the application and customizing it to suit our requirements.

**Comment by trinamic-ed** [comment]
Hello,

sorry, but for now there is no plan to make the TMCL-IDE open-source.

Regards,
    Enrico
